### ISSUE TITLE
Crash on Launch in Modpack

### ISSUE THREAD

**Issue by AshrielV** [glisco03/victus#14]
I'm creating a fabric 0.13.2 modpack in minecraft 1.18.1. I'm receiving this crash when attempting to launch minecraft
[crash-2022-02-16_03.07.50-client.txt](https://github.com/gliscowo/victus/files/8077951/crash-2022-02-16_03.07.50-client.txt)
:

**Comment by gliscowo** [comment]
This is somewhat of a known bug, you'll need to remove Health Overlay if you want to use Victus. Even if they did work together, it is vital for you to be able to judge what hearts you have and as such Health Overlay would make Victus very difficult to properly use once you get more than 10 hearts
Cheers

**Comment by AshrielV** [comment]
Thank you!
