### ISSUE TITLE
Certain heart problems

### ISSUE THREAD

**Issue by gamedevsfowiz123** [glisco03/victus#2]
When using the mod in a 1.17.1 fabric server (0.11.6) whenever a player eats any heart except for the broken ones they get kicked from the server due to "internal server error"

**Comment by gliscowo** [comment]
Could you send the log from the server when this happens? I already have a suspicion what's going on but I need to confirm it

**Comment by gliscowo** [comment]
This should be fixed in 0.1.2, can you confirm that?

**Comment by gamedevsfowiz123** [comment]
Yup, all the issues are fixed in the new version, thanks.
