### ISSUE TITLE
having two totem hearts in a row is broken

### ISSUE THREAD

**Issue by ryleu** [glisco03/victus#20]
if you have two totem hearts in a row and take enough damage to instantly kill you, it deactivates both totem hearts instead of just one

**Comment by gliscowo** [comment]
This isn't a bug, in fact it is perfectly working as intended. When you take enough damage to break an aspect, that aspect will break - whether it can have a useful effect or not. Designing your aspect setup to play nicely with these rules is at the core of the challenge - even if it means that something like the Totem Aspect (deliberately) does not stack very well
Cheers

**Comment by ryleu** [comment]
i guess that makes sense, it just feels bad
