### ISSUE TITLE
Victus incompatible with voxelmap updated

### ISSUE THREAD

**Issue by ayellowlizard** [glisco03/victus#21]
When both victus and [voxelmap updated](https://modrinth.com/mod/voxelmap-updated/version/1.20.1-1.12.13) are installed, it makes the worldmap on voxelmap black, though the minimap works fine.

**Comment by gliscowo** [comment]
This problem is not caused by Victus but instead a bug in owo-lib, which has been fixed in [0.11.2](https://modrinth.com/mod/owo-lib/version/zyOBB7J4)

Cheers, and thanks for reporting
