### ISSUE TITLE
Crafting recipe conflict: Archery Heart and Evoking Heart have the same recipe

### ISSUE THREAD

**Issue by grompe** [glisco03/victus#22]
[Archery Heart Aspect](https://github.com/gliscowo/victus/blob/224e16f0b943809f9a7f6e1a3c6edfb4a9cc9009/src/main/resources/data/victus/recipes/archery_heart_aspect.json) and [Evoking Heart Aspect](https://github.com/gliscowo/victus/blob/224e16f0b943809f9a7f6e1a3c6edfb4a9cc9009/src/main/resources/data/victus/recipes/evoking_heart_aspect.json) have the same crafting recipe, so one is impossible to craft.

**Comment by gliscowo** [comment]
The Evoking Heart Aspect is absolutely craftable, you simply don't use a Crafting Table to do it - as is [clearly outlined in the guide](https://guides.wispforest.io/victus/aspects/evoking/). Thanks for reporting this either way, as the broken recipe for it should certainly be removed

Cheers
